const database = [
    {
        sectorName: "قطاع السياحة",
        sectorCode: "t102",
        sectorIcon: "icon-1.svg",
        sectorN: "tourism",
        info: ["ترخيص عقاري", "الارشاد السياحي", "تنظيم الرحلات السياحية", "حجز وحدات الايواء", "الايواء السياحي"],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "قطاع التعليم",
        sectorCode: "K503",
        sectorIcon: "icon-2.svg",
        sectorN: "industry",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "قطاع الصحة",
        sectorCode: "B201",
        sectorIcon: "icon-3.svg",
        sectorN: "agriculture",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "قطاع النقل",
        sectorCode: "m907",
        sectorIcon: "icon-4.svg",
        sectorN: "trading",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "القطاع البلدي",
        sectorCode: "P001",
        sectorIcon: "icon-5.svg",
        sectorN: "transport",
        info: [],
        desc: "شرح تفصيلي",
    },
      {
        sectorName: "قطاع الاتصالات",
        sectorCode: "P001",
        sectorIcon: "icon-6.svg",
        sectorN: "transport",
        info: [],
        desc: "شرح تفصيلي",
    },
      {
        sectorName: "قطاع التجارة",
        sectorCode: "P001",
        sectorIcon: "icon-7.svg",
        sectorN: "transport",
        info: [],
        desc: "شرح تفصيلي",
    },
      {
        sectorName: "قطاع الاعلام",
        sectorCode: "P001",
        sectorIcon: "icon-8.svg",
        sectorN: "transport",
        info: [],
        desc: "شرح تفصيلي",
    },

];