const database = [
    {
        sectorName: "قطاع السياحة",
        sectorCode: "t102",
        sectorIcon: "icon-1.png",
        sectorN: "tourism",
        info: ["ترخيص عقاري", "الارشاد السياحي", "تنظيم الرحلات السياحية", "حجز وحدات الايواء", "الايواء السياحي"],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "قطاع التعليم",
        sectorCode: "K503",
        sectorIcon: "icon-2.png",
        sectorN: "education",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "قطاع الصحة",
        sectorCode: "B201",
        sectorIcon: "icon-3.png",
        sectorN: "health",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "قطاع النقل<br/> والخدمات اللوجستية",
        sectorCode: "m907",
        sectorIcon: "icon-4.png",
        sectorN: "transport",
        info: [],
        desc: "شرح تفصيلي",
    },

    {
        sectorName: "قطاع البلدية",
        sectorCode: "P001",
        sectorIcon: "icon-5.png",
        sectorN: "municipality",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "قطاع الاتصالات<br/> وتقنية المعلومات",
        sectorCode: "P001",
        sectorIcon: "icon-6.png",
        sectorN: "telecom",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "قطاع الترفيه",
        sectorCode: "P001",
        sectorIcon: "icon-7.png",
        sectorN: "media",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "قطاع الإعلام",
        sectorCode: "P001",
        sectorIcon: "icon-8.png",
        sectorN: "media",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "قطاع <br>الصناعات العسكرية",
        sectorCode: "P001",
        sectorIcon: "icon-9.png",
        sectorN: "media",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "قطاع<br> الغذاء والدواء",
        sectorCode: "P001",
        sectorIcon: "icon-10.png",
        sectorN: "media",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "قطاع الصناعة",
        sectorCode: "P001",
        sectorIcon: "icon-11.png",
        sectorN: "trade",
        info: [],
        desc: "شرح تفصيلي",
    },
    {
        sectorName: "قطاع الرياضة",
        sectorCode: "P001",
        sectorIcon: "icon-12.png",
        sectorN: "media",
        info: [],
        desc: "شرح تفصيلي",
    },

];

const tbl_tourism = [
    {
        tId: "t102",
        tName: "الفنادق",
        tCode: "551011",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "الفنادق التراثية",
        tCode: "551013",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "فنادق الاستشفاء",
        tCode: "551014",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "فنادق البوتيك",
        tCode: "551015",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "الفلل الفندقية",
        tCode: "551023",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "الشقق المخدومة",
        tCode: "551025",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "بيوت العطلات (الشاليهات)",
        tCode: "551041",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "النزل السياحية",
        tCode: "551043",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "المنتجعات",
        tCode: "551044",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "وحدات المشاركة بالوقت",
        tCode: "551060",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "فنادق الكبائن",
        tCode: "551071",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "إدارة مرافق الإيواء السياحي",
        tCode: "551081",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "المخيمات",
        tCode: "552001",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "أنشطة وكالات السياحة والسفر",
        tCode: "791101",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "تنظيم رحلات سياحية",
        tCode: "791223",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "أنشطة الأدلاء السياحيين",
        tCode: "791224",
        tIcon: "icon-1.svg",
        tdesc: "",
    },
    {
        tId: "t102",
        tName: "حجز وحدات الإيواء السياحي وتسويقها",
        tCode: "799014",
        tIcon: "icon-1.svg",
        tdesc: "",
    },

];